baseURL: https://karlz97.github.io/cnblog
languageCode: zh-cn
title: 随机脑噪音
theme: "PaperMod"

params:
  homeInfoParams:
    Title: 随机脑噪音
    Content: 策马扬鞭，与时俱进。行道迟迟，载渴载饥。
    Hi! This is Karl Zhang.
    I love coding, rock climbing, and cooking.
    I’m a Master’s student in Industrial Engineering at Purdue University. I received my undergraduate degree in Computation Mathematics from the Ocean University of China and am proud of being the first batch of students of Xingyuan College.
    I am passionate about building things. My current focus is on software development, machine learning, and operations research. I am still new to software development and machine learning, both of which I am trying to teach myself. My Master’s research is exploring the possibility of using drones to lift the efficiency of meal delivery.
    Besides, I also have a wide interest in sociology, history, and anthropology.
    
  socialIcons: # optional
    - name: "github"
      url: "https://github.com/XXX"
    # - name: "youtube"
    #   url: "https://www.youtube.com/channel/XXX"
    - name: "twitter"
      url: "https://twitter.com/XXX"
    - name: "cv"
      url: "https://karlz97.github.io/"
#     - name: "linkedin"
#       url: "https://www.linkedin.com/in/yindingzhang97/"
    # - name: "kofi"
    #   url: "https://buymeacoffee.com/XXX"
    # - name: "rss"
    #   url: "https://XXX.github.io/index.xml"
  ShowReadingTime: true
  author: "Karl Zhang"
  contact: "yindingzhang@gmail.com"
  feedlinks: true
  copyright: "<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->"
  mobileMenu: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
  section:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: categories
      name: 类别
      url: /categories/
      weight: 10
    - identifier: tags
      name: 标签
      url: /tags/
      weight: 20
    - identifier: search
      name: 搜索
      url: /search/
      weight: 20
    - identifier: archive
      name: 存档
      url: /archives/
      weight: 20
#     - identifier: aboutme
#       name: About
#       url: "https://karlz97.github.io/"
#       weight: 20
