baseURL: https://githubuser.github.io
languageCode: en-us
title: Linus Torvalds
theme: "PaperMod"

params:
  homeInfoParams:
    Title: 随机脑噪音
    Content: 策马扬鞭，与时俱进。行道迟迟，载渴载饥。

  socialIcons: # optional
    - name: "github"
      url: "https://github.com/XXX"
    # - name: "youtube"
    #   url: "https://www.youtube.com/channel/XXX"
    - name: "twitter"
      url: "https://twitter.com/XXX"
    - name: "cv"
      url: "https://twitter.com/XXX"
    - name: "blog"
      url: "https://twitter.com/XXX"
    # - name: "kofi"
    #   url: "https://buymeacoffee.com/XXX"
    # - name: "rss"
    #   url: "https://XXX.github.io/index.xml"
  ShowReadingTime: true
  author: "Karl Zhang"
  contact: "yindingzhang@gmail.com"
  feedlinks: true
  copyright: "<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->"
  mobileMenu: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
  section:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 20
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 20
    - identifier: aboutme
      name: About
      url: "https://karlz97.github.io/"
      weight: 20
